# English quenya translation using a transformer - Data collection

## Main page

In [1]:
import requests
from bs4 import BeautifulSoup
import numpy as np
import nltk
import torch
from torch.utils.data import TensorDataset, DataLoader
import torch.optim as optim
import torch.nn
import torch.nn.functional as F
from model import Transformer
from sklearn.model_selection import train_test_split

#Importing all of the necessary libraries

url = "https://eldamo.org/content/phrase-indexes/phrases-q.html"
r = requests.get(url)

In [2]:
soup = BeautifulSoup(r.content, 'html.parser')

In [3]:
rows_english = soup.select('li')

In [4]:
rows_english[50].text

'A anamelda na ar ilyan  “A is dearest of all”\n               '

In [5]:
quenya_sentences =[]
for row in rows_english:
    quenya_sentences.append(row.text)

In [6]:
sentences = quenya_sentences[15:]

In [7]:
sentences_english = []
sentences_quenya = []
for sentence in sentences:
    compteur = 0
    for i in range(len(sentence)): #separating the lines to get the english and quenya parallel sentences
        if sentence[i]=="“": 
            beginning = i+1
        if sentence[i]=="”":
            ending = i #allows to find where the english sentence is located in the string
            last_ending = ending
            compteur+=1
            sentences_english.append(sentence[beginning:ending])
            if compteur==1:
                sentences_quenya.append(sentence[:beginning])
            else:
                sentences_quenya.append(sentence[last_ending:beginning])
                

## Poems & prayers found on the website

In [10]:
list_url = ["https://eldamo.org/content/words/word-2555725393.html", "https://eldamo.org/content/words/word-2245526111.html",
            "https://eldamo.org/content/words/word-671674147.html", "https://eldamo.org/content/words/word-311699583.html",
            "https://eldamo.org/content/words/word-2920398593.html", "https://eldamo.org/content/words/word-3295893985.html",
            "https://eldamo.org/content/words/word-2124111669.html", "https://eldamo.org/content/words/word-4161205007.html",
            "https://eldamo.org/content/words/word-436003197.html", "https://eldamo.org/content/words/word-2774144071.html",
            "https://eldamo.org/content/words/word-3330342599.html", "https://eldamo.org/content/words/word-1216507117.html",
            "https://eldamo.org/content/words/word-2721399773.html", "https://eldamo.org/content/words/word-1235857611.html"]
for url in list_url:
    r = requests.get(url)
    soup = BeautifulSoup(r.content, 'html.parser')
    rows_english = soup.select('td')
    for i in range(0,len(rows_english)):
        if i%2==0:
            sentences_quenya.append(rows_english[i].text)
        else:
            sentences_english.append(rows_english[i].text)

## Dictionary pulled from Eldamo

In [13]:
url = "https://eldamo.org/content/vocabulary-indexes/vocabulary-words-nq.html?neo"
r = requests.get(url)
soup = BeautifulSoup(r.content, 'html.parser')
rows = soup.select('dt')

In [14]:
words = []
for row in rows:
    words.append(row.text)
    

In [15]:
words_english = []
words_quenya = []
for word in words:
    compteur=0
    for i in range(len(word)):
        if ((word[i]==" ") | (word[i]=="-"))&(compteur==0)&(i!=0): #separating the data according to its structure on the website
            ending_quenya = i
            words_quenya.append(word[:ending_quenya])
            compteur+=1
        if word[i]=="“":
            beginning = i+1 
        if word[i]=="”":
            ending = i
            words_english.append(word[beginning:ending])
            break
            
            

In [18]:
sentences_english = np.concatenate([sentences_english, words_english])

In [19]:
sentences_quenya = np.concatenate([sentences_quenya, words_quenya])

In [20]:
list_english = []
list_quenya = []
for sentence in sentences_english:
    list_english.append(list(sentence))
for sentence in sentences_quenya:
    list_quenya.append(list(sentence))

In [21]:
m = 0
for i in range(len(sentences_english)): #finding the maximum length for a sentence
    if len(list_english[i])>m: 
        m = len(list_english[i])
    if len(list_quenya[i])>m:
        m = len(list_quenya[i])

## Tokenization

In [23]:
char2index = {} #preparing the dictionaries for tokenization
index2char = {}
counter = 1
for i in range(len(sentences_english)):
    sent_english = sentences_english[i]
    sent_quenya = sentences_quenya[i]
    for w in sent_english:
        if w not in char2index:
            counter+=1
            char2index[w] = counter
            index2char[counter] = w
    for w in sent_quenya:
        if w not in char2index:
            counter+=1
            char2index[w] = counter
            index2char[counter] = w
char2index['<EOS>'] = counter+1
index2char[counter+1] = '<EOS>' 

In [24]:
data_en = np.zeros([len(list_english), m+1]) #preparing the dataset. 0 is the padding token.
data_quenya = np.zeros([len(list_english), m+1])
data_quenya.shape

(5574, 147)

In [25]:
for i in range(len(list_english)): #adding <EOS> token at the end of each sentence
    for j in range(len(list_english[i])):
        data_en[i,j] = char2index[list_english[i][j]]
    data_en[i,len(list_english[i])] = char2index['<EOS>']
    for j in range(len(list_quenya[i])):
        data_quenya[i,j] = char2index[list_quenya[i][j]]
    data_quenya[i,len(list_quenya[i])] = char2index['<EOS>']

In [26]:
a = np.zeros(147) #checking for empty sentences which cause an issue if fed to the multihead attention layers with a padding mask

In [27]:
L=[]
for d in range(len(data_quenya)):
    if np.array_equal(a,data_quenya[d]):
        L.append(d)

In [28]:
data_en = np.delete(data_en,L,0)
data_quenya = np.delete(data_quenya,L,0)

# Model definition

In [30]:
DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [31]:
VOC_SIZE = len(char2index)+2
EMB_SIZE = 512
NHEAD = 4
HID_DIM = 1024
BATCH_SIZE = 40
NUM_ENCODER_LAYERS = 4
NUM_DECODER_LAYERS = 4 #model hyperparameters

In [32]:
transformer = Transformer(NUM_ENCODER_LAYERS, NUM_DECODER_LAYERS, EMB_SIZE, NHEAD, HID_DIM, 0.01, VOC_SIZE)#model definition

In [33]:
transformer = transformer.to(DEVICE)

In [34]:
en_train, en_test, qu_train, qu_test = train_test_split(data_en, data_quenya, test_size = 0.2)

In [35]:
en_train = torch.Tensor(en_train).long() 
en_test = torch.Tensor(en_test).long()
qu_train = torch.Tensor(qu_train).long()
qu_test = torch.Tensor(qu_test).long()

In [36]:
train_dataset = TensorDataset(en_train, qu_train)
test_dataset = TensorDataset(en_test, qu_test)

In [37]:
train_dataloader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=False)

## Masks creation

In [38]:
def positionalEncoding(length, embed_dim): #positionalEncoding as described in the original paper
    angles = np.array([[pos/10000**(2*(i//2)) for i in range(embed_dim)] for pos in range(length)])
    pos_encoding = np.zeros((length, embed_dim))
    pos_encoding[:,0::2] = np.sin(angles[:,0::2])
    pos_encoding[:,1::2] = np.cos(angles[:,1::2])
    return torch.from_numpy(pos_encoding)

In [39]:
def create_look_ahead_mask(size): #attention mask for multi head attention
    mask = torch.triu(torch.ones(size, size), diagonal=1).to(torch.bool)
    return mask

In [40]:
def padding_mask(x):
    return x==0

In [41]:
pos_encoding = positionalEncoding(m+1, EMB_SIZE).to(DEVICE)
attn_mask = create_look_ahead_mask(m+1).to(DEVICE)


## Training

In [ ]:
criterion = torch.nn.CrossEntropyLoss()#training loop
transformer.train()
num_epochs = 10
optimizer = torch.optim.Adam(transformer.parameters(), lr=1e-5)
torch.autograd.set_detect_anomaly(True) 
for epoch in range(num_epochs):
    # Iterate over the batches in the train_dataloader
    for batch_idx, batch in enumerate(train_dataloader):
        # Get the batch of input sentences and labels
        sentences = batch[0].to(DEVICE)
        labels = batch[1].to(DEVICE)
        src_padding_mask = padding_mask(sentences).to(DEVICE)
        tgt_padding_mask = padding_mask(labels).to(DEVICE)
        # Reset the gradients
        
        optimizer.zero_grad()
        # Forward pass
        outputs = transformer(sentences, labels, src_padding_mask, tgt_padding_mask, attn_mask, pos_encoding)
        
        # Compute the loss
        loss = criterion(outputs.view(-1,VOC_SIZE,m+1), labels)
        torch.nn.utils.clip_grad_norm_(transformer.parameters(), 0.5)

        # Backward pass
        loss.backward()
        # Update the weights
        optimizer.step()

        # Print the loss every 5 batches
        if (batch_idx + 1) % 5 == 0:
            print('Epoch [{}/{}], Batch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, batch_idx+1, len(train_dataloader), loss.item()))

Epoch [1/10], Batch [5/112], Loss: 4.7044
Epoch [1/10], Batch [10/112], Loss: 4.7013
Epoch [1/10], Batch [15/112], Loss: 4.7009
Epoch [1/10], Batch [20/112], Loss: 4.7029
Epoch [1/10], Batch [25/112], Loss: 4.7039
Epoch [1/10], Batch [30/112], Loss: 4.7025
Epoch [1/10], Batch [35/112], Loss: 4.7015
Epoch [1/10], Batch [40/112], Loss: 4.7009
Epoch [1/10], Batch [45/112], Loss: 4.7012
Epoch [1/10], Batch [50/112], Loss: 4.7015
Epoch [1/10], Batch [55/112], Loss: 4.7033
Epoch [1/10], Batch [60/112], Loss: 4.7056
Epoch [1/10], Batch [65/112], Loss: 4.7020
Epoch [1/10], Batch [70/112], Loss: 4.7050
Epoch [1/10], Batch [75/112], Loss: 4.7020
Epoch [1/10], Batch [80/112], Loss: 4.7008
Epoch [1/10], Batch [85/112], Loss: 4.7003
Epoch [1/10], Batch [90/112], Loss: 4.7019
Epoch [1/10], Batch [95/112], Loss: 4.7024
Epoch [1/10], Batch [100/112], Loss: 4.7009
Epoch [1/10], Batch [105/112], Loss: 4.7059
Epoch [1/10], Batch [110/112], Loss: 4.7026
Epoch [2/10], Batch [5/112], Loss: 4.7044
Epoch [2/1

## Inference

In [43]:
transformer.train(mode=False)

Transformer(
  (encoder): Encoder(
    (layers): ModuleList(
      (0): EncoderLayer(
        (mha): MultiheadAttention(
          (out_proj): NonDynamicallyQuantizableLinear(in_features=512, out_features=512, bias=True)
        )
        (norm1): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
        (fullyconnected1): Linear(in_features=512, out_features=1024, bias=True)
        (relu): ReLU()
        (fullyconnected2): Linear(in_features=1024, out_features=512, bias=True)
        (norm2): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
      )
      (1): EncoderLayer(
        (mha): MultiheadAttention(
          (out_proj): NonDynamicallyQuantizableLinear(in_features=512, out_features=512, bias=True)
        )
        (norm1): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
        (fullyconnected1): Linear(in_features=512, out_features=1024, bias=True)
        (relu): ReLU()
        (fullyconnected2): Linear(in_features=1024, out_features=512, bias=True)
        

In [96]:
input_sentence = np.zeros(m+1) #inference
output_sentence = np.zeros(m+1)
generated_sentence = []
my_sentence = "This is a test sentence"
for i in range(len(my_sentence)):
    input_sentence[i] = char2index[my_sentence[i]] #tokenization of the input sentence and adding EOS token
input_sentence[len(my_sentence)]=char2index['<EOS>']
input_sentence = torch.Tensor(input_sentence).long().to(DEVICE)
output_sentence = torch.Tensor(output_sentence).long().to(DEVICE)
output_sentence[0]=0

In [97]:
src_padding_mask = padding_mask(input_sentence)
s=1
generated_letter = 0 #we need to put something as the output in the model
while (len(generated_sentence))<m+1 and (generated_letter!=char2index['<EOS>']):
    tgt_padding_mask = padding_mask(output_sentence)
    tgt_padding_mask[0]=False #a fully True mask causes NaN values in the softmax layer
    print(output_sentence)
    last_output = transformer(input_sentence, output_sentence, src_padding_mask, tgt_padding_mask, attn_mask, pos_encoding)
    last_output = torch.argmax(last_output, -1)
    generated_letter = last_output[s]
    generated_sentence.append(generated_letter)
    output_sentence[s] = generated_letter #loop over the generated sentence, character after character
    s+=1


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0], device='cuda:0')
tensor([ 0, 31,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
     

tensor([ 0, 31, 91, 81,  2, 15, 92, 92, 31, 40, 33, 77, 92, 92,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0], device='cuda:0')
tensor([ 0, 31, 91, 81,  2, 15, 92, 92, 31, 40, 33, 77, 92, 92, 92,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
  

In [98]:

L=[]
for c in output_sentence:
    if c.item()!=0:
        L.append(index2char[c.item()])
print(L)
''.join(L) #print the generated sentence

['ó', '\n', 'î', 'H', 'A', '—', '—', 'ó', 'C', ')', 'P', '—', '—', '—', ';', '²', 'C', '—', '—', '—']


'ó\nîHA——óC)P———;²C———'

In [57]:
char2index['']=0

In [58]:
index2char[0]=''

In [103]:
torch.save(transformer.state_dict(), ".\saved_model")

Note: I can only train the model for a few hours, it is relatively small and I have very little available data. Obviously, the use of transfer training would have been preferrable here, because the results are really bad (no metrics needed to realise this). I just did this as a fun project to use pytorch a bit.